### ISSUE TITLE
Uses math.random instead of crypto.randomBytes()

### ISSUE THREAD

**Issue by runvnc** [danmactough/node-randpass#1]
Hello, I am using your module in my login-mongo module and I got slammed by one guy on reddit.com/r/node http://www.reddit.com/r/node/comments/1psqwd/loginmongo_a_simple_mongodbbased_backend_for/.  One of the things that he hates is that this uses Math.random().  Apparently my module is incredibly disliked on reddit.com/r/node.  Obviously the other things I did in there contributed a lot to how much he doesn't like it.  But I thought I would mention to you in case you wanted to use a different way of getting random numbers.

**Comment by danmactough** [comment]
I don't know how you're using this module, but it's definitely not a crypto module. It's barely "random" in any sense -- it makes a point of directing the outcome of each "random" outcome to ensure that the result is pronounceable.

But being attacked on reddit doesn't always mean you've done something wrong. :)

**Comment by runvnc** [comment]
Using it to generate a random temporary password as a reset when they
forget their password.  Good point about reddit.

**Comment by danmactough** [comment]
For that use case, it's FAR more important to have retry throttling, one-time use, and short life.
